# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('country_code', models.CharField(max_length=3)),
                ('district', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=52)),
                ('continent', models.CharField(max_length=13)),
                ('region', models.CharField(max_length=26)),
                ('surface_area', models.FloatField()),
                ('indep_year', models.SmallIntegerField(blank=True, null=True)),
                ('population', models.IntegerField()),
                ('life_expectancy', models.FloatField(blank=True, null=True)),
                ('gnp', models.FloatField(blank=True, null=True)),
                ('gnp_old', models.FloatField(blank=True, null=True)),
                ('local_name', models.CharField(max_length=45)),
                ('government_form', models.CharField(max_length=45)),
                ('head_of_state', models.CharField(blank=True, max_length=60, null=True)),
                ('capital', models.IntegerField(blank=True, null=True)),
                ('code2', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('language', models.CharField(max_length=30)),
                ('is_official', models.CharField(max_length=1)),
                ('percentage', models.FloatField()),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
    ]
